config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  devise_for :users, controllers: {registrations: "users/registrations"}
  resources :users, except: [:destroy]
  resources :courses do
    resources :examinations, only: [:show, :update]
  end
  resources :examinations, only: [:create]

  namespace :admin do
    root 'static_pages#home'
    resources :courses
    resources :users
  end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    return unless current_user
    @examinations = current_user.examinations.paginate(page: params[:page],
                                                       per_page: 10)
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/static_pages/home.html.erb
<%= content_tag :div, class: "row" do %>
  <%= content_tag :div, class: "center jumbotron" do %>
    <%= content_tag :h1, "Welcome! You are our admin" %>
    <%= content_tag :h2, "This is the home page" %>
    <%= link_to "Create user", new_admin_user_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "List all course", admin_courses_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "Create course", new_admin_course_path, class: "btn btn-lg btn-primary" %>
  <% end %>
<% end %>