config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  devise_for :users, controllers: {registrations: "users/registrations"}
  resources :users, except: [:destroy]
  resources :courses do
    resources :examinations, only: [:show, :update]
  end
  resources :examinations, only: [:create]

  namespace :admin do
    root 'static_pages#home'
    resources :courses
    resources :users
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  ROLES = %w(admin normal)

  has_many :examinations, dependent: :destroy

  validates :name, presence: true, length: {maximum:50}
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :role, presence: true, inclusion: {in: ROLES}
  validate :avatar_size

  ROLES.each do |role|
    define_method("is_#{role}?") do
      self.role == role
    end
  end

  private
  def avatar_size
    errors.add(:avatar, "should be less than 1MB") if avatar.size > 1.megabytes
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def new
  end

  def create
    if @user.save
      flash[:success] = "User created!"
      redirect_to users_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update_attributes update_params
      flash[:success] = 'Profile updated'
      redirect_to admin_root_path
    else
      render 'edit'
    end
  end

  def destroy
    @user.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to admin_root_path
  end

  private
  def create_params
    params.require(:user).permit(:name, :email,
                                 :password, :password_confirmation,
                                 :role, :avatar, :avatar_cache)
  end

  def update_params
    create_params.delete_if{|_, v| v.blank?}
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << [:name, :avatar, :avatar_cache]
  end

  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << [:name, :avatar,
                                                        :avatar_cache]
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @users = @users.paginate page: params[:page]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def avatar_for user, options = {size: 50}
    size = options[:size]
    name = options[:name] || user.name
    url = size <= 50 ? user.avatar.thumb.url : user.avatar.url
    image_tag(url, alt: name, title: name, size: "#{size}x#{size}",
             class: "avatar")
  end
end

app/views/admin/users/edit.html.erb
<% provide :title, "Edit #{@user.name.to_s}" %>
<%= content_tag :h1, yield(:title) %>

<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <%= form_for @user, url: admin_user_path do |f| %>
      Name: <%= f.text_field :name, autofocus: true, class: "form-control" %>
      Email: <%= f.email_field :email, class: "form-control" %>
      Password: <%= f.password_field :password,
        autocomplete: "off", class: "form-control" %>
      Password confirmation: <%= f.password_field :password_confirmation,
        autocomplete: "off", class: "form-control" %>
      Avatar: <%= image_tag(@user.avatar.thumb.url) if @user.avatar? %>
      <%= f.file_field :avatar, accept: "image/jpeg,image/gif,image/png" %>
      <%= f.hidden_field :avatar_cache %>
      Role: <%= f.select :role do %>
        <%= content_tag :option, "Normal", value: "normal" %>
        <%= content_tag :option, "Admin", value: "admin" %>
      <% end %>
      <%= f.submit "Update", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/users/new.html.erb
<% provide :title, "Create course" %>
<%= content_tag :h1, yield(:title) %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: admin_users_path do |f| %>
      Name: <%= f.text_field :name, autofocus: true, class: "form-control" %>
      Email: <%= f.email_field :email, class: "form-control" %>
      Password: <%= f.password_field :password,
        autocomplete: "off", class: "form-control" %>
      Password confirmation: <%= f.password_field :password_confirmation,
        autocomplete: "off", class: "form-control" %>
      Avatar: <%= image_tag(@user.avatar.thumb.url) if @user.avatar? %>
      <%= f.file_field :avatar, accept: "image/jpeg,image/gif,image/png" %>
      <%= f.hidden_field :avatar_cache %>
      Role: <%= f.select :role do %>
        <%= content_tag :option, "Normal", value: "normal" %>
        <%= content_tag :option, "Admin", value: "admin" %>
      <% end %>
      <%= f.submit "Sign up", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>