config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  devise_for :users, controllers: {registrations: "users/registrations"}
  resources :users, except: [:destroy]
  resources :courses do
    resources :examinations, only: [:show, :update]
  end
  resources :examinations, only: [:create]

  namespace :admin do
    root 'static_pages#home'
    resources :courses
    resources :users
  end
end

app/views/layouts/_footer.html.erb
<%= content_tag :footer, class: "footer" do %>
  <%= content_tag :small do %>
    The E-learning System
  <% end %>
  <%= content_tag :nav do %>
    <%= content_tag :ul do %>
      <%= content_tag :li do %>
        <%= link_to "About", about_path %>
      <% end %>
      <%= content_tag :li do %>
        <%= link_to "Contact", contact_path %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<%= content_tag :header, class: "navbar navbar-fixed-top navbar-inverse" do %>
  <%= content_tag :div, class: "container" do %>
    <%= link_to "E-learning", current_user && current_user.is_admin? ? admin_root_path : root_path,
                            id: "logo" %>
    <%= content_tag :nav do %>
      <%= content_tag :ul, class: "nav navbar-nav navbar-right" do %>
        <%= content_tag :li do %>
          <%= link_to "Home", current_user && current_user.is_admin? ? admin_root_path : root_path %>
        <% end %>
        <%= content_tag :li do %>
          <%= link_to "Help", help_path %>
        <% end %>
        <% if user_signed_in? %>
          <%= content_tag :li do %>
            <%= link_to "Users", users_path %>
          <% end %>
          <%= content_tag :li, class: "dropdown" do %>
            <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
              <%= avatar_for current_user, size: 20 %>
              <%= current_user.name.split[0] %>
              <%= content_tag :b, '', class: "caret" %>
            <% end %>
            <%= content_tag :ul, class: "dropdown-menu" do %>
              <%= content_tag :li do %>
                <%= link_to "Profile", "#" %>
              <% end %>
              <%= content_tag :li do %>
                <%= link_to "Settings", edit_user_registration_path(current_user) %>
              <% end %>
              <%= content_tag :li, '', class: "divider" %>
              <%= content_tag :li do %>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              <% end %>
            <% end %>
          <% end %>
        <% else %>
          <%= content_tag :li do %>
            <%= link_to "Log in", new_user_session_path %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= content_tag :html do %>
  <%= content_tag :head do %>
    <%= content_tag :title do %>
      <%= full_title(yield(:title)) %>
    <% end %>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  <% end %>
  <%= content_tag :body do %>
    <%= render 'layouts/header' %>
    <%= content_tag :div, class: "container" do %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message,
                        class: "alert alert-#{alert_type message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    <% end %>
  <% end %>
<% end %>